### ISSUE TITLE
Questions 2 and 9 are not complete questions

### ISSUE THREAD

**Issue by hoyzington** [learn-co-curriculum/programming-univbasics-nds-final-quiz#3]

**Comment by maxwellbenton** [comment]
Hi @hoyzington,

Thank you for opening this issue. I've taken a look at questions 2 and 9, but unfortunately, I am unclear as to what you mean as not complete. Question 9 is a bit of a 'gotcha' type question, but both questions appear to be valid upon review. I've updated the wording on question 2 to help avoid confusion.

Since it appears there is no issue currently with these questions, I am going to close this issue. However, if you can provide additional information, please feel free to re-open this issue and I will take a look.

Thank you!
